[package]
name = "rust_topojson_client"
version = "0.1.0"
edition = { workspace=true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
js = ["dep:getrandom"]

[dependencies]
geo = { workspace = true }
# Create a shadow dependency on getrandom with the feature "js"
# In effect this will add the "js" feature flag to the real depedency
# d3_geo_rs->geo->rand->genrandom
getrandom = { version = "0.2.16", features = ["js"], optional=true}


topojson = { workspace = true }

[dev-dependencies]
pretty_assertions = "~1"
criterion = "~0.8"
serde_json = { workspace = true }
serde = { workspace = true }

[[bench]]
name = "world"
harness = false
