name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: MachineDynamo/rust-action@master
        with:
          # args: cargo fmt -- --check && cargo clippy -- -Dwarnings && cargo test --verbose
          args: cargo fmt --check && cargo clippy && cargo test
